/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Ricardo
 */
public class InterfazGerente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGerente
     */
    public InterfazGerente() {
        initComponents();
        this.setLocationRelativeTo(null);                       // centramos la ventana en la pantalla
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonGestionSedes = new javax.swing.JButton();
        jButtonListarSedes = new javax.swing.JButton();
        jButtonGestionEventos = new javax.swing.JButton();
        jButtonListarEventos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido, Gerente");

        jButtonGestionSedes.setText("Sedes");
        jButtonGestionSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionSedesActionPerformed(evt);
            }
        });

        jButtonListarSedes.setText("Listar Sedes");
        jButtonListarSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarSedesActionPerformed(evt);
            }
        });

        jButtonGestionEventos.setText("Eventos");
        jButtonGestionEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionEventosActionPerformed(evt);
            }
        });

        jButtonListarEventos.setText("Listar Eventos");
        jButtonListarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEventosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGestionSedes)
                .addGap(18, 18, 18)
                .addComponent(jButtonGestionEventos)
                .addGap(18, 18, 18)
                .addComponent(jButtonListarSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGestionSedes)
                    .addComponent(jButtonGestionEventos)
                    .addComponent(jButtonListarSedes)
                    .addComponent(jButtonListarEventos))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionSedesActionPerformed
        // TODO add your handling code here:
        RegistrarSedes registrarSedes = new RegistrarSedes();
        registrarSedes.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGestionSedesActionPerformed

    private void jButtonListarSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarSedesActionPerformed
        // TODO add your handling code here:
        ListarSedes listarSedes = new ListarSedes();
        listarSedes.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonListarSedesActionPerformed

    private void jButtonGestionEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionEventosActionPerformed
        // TODO add your handling code here:
        RegistrarEventos registrarEventos = new RegistrarEventos();
        registrarEventos.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGestionEventosActionPerformed

    private void jButtonListarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEventosActionPerformed
        // TODO add your handling code here:
        ListarEventos listarEventos = new ListarEventos();
        listarEventos.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonListarEventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionEventos;
    private javax.swing.JButton jButtonGestionSedes;
    private javax.swing.JButton jButtonListarEventos;
    private javax.swing.JButton jButtonListarSedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
