/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JDateChooser;
import controladores.ControladorSede;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class RegistrarSedes extends JFrame {

    private String identificacion;
    private String id_empleado;
    private String nombre;
    private String direccion;
    private String telefono;
    private String fecha_creacion;
    ControladorSede ControladorSede = new ControladorSede();

    @Override
    public void setDefaultCloseOperation(int i) {
        super.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form RegistrarSedes
     */
    public RegistrarSedes() {
        initComponents();
        setResizable(false);
        iniciarComponentes();
        limpiarCampos();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldIdEmpleado = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldFechaCreacion = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jRadioRegistrar = new javax.swing.JRadioButton();
        jRadioModificar = new javax.swing.JRadioButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Sedes");

        jLabel2.setText("Identificacion");

        jLabel3.setText("Id empleado");

        jLabel4.setText("Nombre");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        jLabel7.setText("Fecha Creacion");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jRadioRegistrar.setText("Registrar");
        jRadioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRegistrarActionPerformed(evt);
            }
        });

        jRadioModificar.setText("Modificar");
        jRadioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioModificarActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldIdEmpleado)
                            .addComponent(jTextFieldIdentificacion)
                            .addComponent(jTextFieldDireccion)
                            .addComponent(jTextFieldTelefono)
                            .addComponent(jTextFieldFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButtonOk)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioRegistrar)
                    .addComponent(jRadioModificar))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jRadioRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonBuscar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void iniciarComponentes() {
        identificacion = "";
        id_empleado = "";
        nombre = "";
        direccion = "";
        telefono = "";
        fecha_creacion = "";
        jButtonBuscar.setEnabled(false);
    }

    public final void limpiarCampos() {
        jTextFieldIdentificacion.setText("");
        jTextFieldIdEmpleado.setText("");
        jTextFieldNombre.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldFechaCreacion.setText("");
    }

    public void tomarCampos() {
        identificacion = jTextFieldIdentificacion.getText();
        id_empleado = jTextFieldIdEmpleado.getText();
        nombre = jTextFieldNombre.getText();
        direccion = jTextFieldDireccion.getText();
        telefono = jTextFieldTelefono.getText();
        fecha_creacion = jTextFieldFechaCreacion.getText();
    }

    public int validarCampos() {
        identificacion = jTextFieldIdentificacion.getText();
        id_empleado = jTextFieldIdEmpleado.getText();
        nombre = jTextFieldNombre.getText();
        direccion = jTextFieldDireccion.getText();
        telefono = jTextFieldTelefono.getText();
        fecha_creacion = jTextFieldFechaCreacion.getText();
        if (identificacion.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", identificacion)) {
            return 1;
        } else if (id_empleado.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", id_empleado)) {
            return 2;
        } else if (nombre.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[a-zA-Z ]+", nombre)) {
            return 3;
        } else if (direccion.isEmpty()) {
            return 7;
        } else if (!direccion.contains("#")
                || !direccion.contains("-")
                || !direccion.contains("Cra")
                || !direccion.contains("Calle")
                || direccion.equals("")) {
            return 4;
        } else if (telefono.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", telefono)) {
            return 5;
        } else if (fecha_creacion.isEmpty()) {
            return 7;
        } else if (!fecha_creacion.contains("-") || !fecha_creacion.contains(":")) {
            return 6;
        }
        return 0;
    }

    public void habilitarBotones() {
        jRadioModificar.setEnabled(true);
        jRadioRegistrar.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonOk.setEnabled(true);
        jTextFieldDireccion.setEditable(true);
        jTextFieldFechaCreacion.setEditable(true);
        jTextFieldIdEmpleado.setEditable(true);
        jTextFieldIdentificacion.setEditable(true);
        jTextFieldNombre.setEditable(true);
        jTextFieldTelefono.setEditable(true);
        jRadioModificar.setSelected(false);
        jRadioRegistrar.setSelected(false);
    }
    private void jRadioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRegistrarActionPerformed
        // TODO add your handling code here:
        jRadioModificar.setEnabled(false);
    }//GEN-LAST:event_jRadioRegistrarActionPerformed

    private void mostrarMensajesValidaciones(int numero) {
        switch (numero) {
            case 1:
                JOptionPane.showMessageDialog(null, "El campo identifiacion sólo debe contener números");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "El campo id empleado sólo debe contener números");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "El campo nombre sólo debe contener letras");
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "La dirección no permite letras o caracteres especiales");
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "El campo telefono sólo debe contener números");
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "La fecha de creación no permite letras o caracteres especiales");
                break;
            case 7:
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
                break;
            case 0:
                JOptionPane.showMessageDialog(null, "Éxito");
                limpiarCampos();
                break;
            default:
                break;
        }
    }
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        if (jRadioRegistrar.isSelected()) {
            tomarCampos();
            int respuesta = validarCampos();
            mostrarMensajesValidaciones(respuesta);
            if (respuesta == 0) {
                ControladorSede.registrarSede(identificacion, id_empleado, nombre, direccion, telefono, fecha_creacion);
                limpiarCampos();
                habilitarBotones();
            }
        }
        if (jRadioModificar.isSelected()) {
            tomarCampos();
            int respuesta = validarCampos();
            mostrarMensajesValidaciones(respuesta);
            if (respuesta == 0) {
                ControladorSede.editarSede(identificacion, id_empleado, nombre, direccion, telefono, fecha_creacion);
                limpiarCampos();
                habilitarBotones();
            }
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    /*private void validarBeta()
    {
        ControladorSede controlador = new ControladorSede() ;
        controlador.validarDatosModif(identificacion, id_empleado, nombre, direccion, telefono, fecha_creacion);
    }*/
    private void eventosModificar() {
        jRadioRegistrar.setEnabled(false);
        jRadioRegistrar.setSelected(false);
        jButtonOk.setEnabled(false);
        jButtonCancel.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        jTextFieldIdEmpleado.setEditable(false);
        jTextFieldNombre.setEditable(false);
        jTextFieldDireccion.setEditable(false);
        jTextFieldTelefono.setEditable(false);
        jTextFieldFechaCreacion.setEditable(false);
    }

    private void eventosBuscar() {
        jTextFieldIdentificacion.setEditable(false);
        jTextFieldIdEmpleado.setEditable(true);
        jTextFieldNombre.setEditable(true);
        jTextFieldDireccion.setEditable(true);
        jTextFieldTelefono.setEditable(true);
        jTextFieldFechaCreacion.setEditable(true);
        jButtonBuscar.setEnabled(false);
        jButtonOk.setEnabled(true);
    }

    private void jRadioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioModificarActionPerformed
        // TODO add your handling code here:
        eventosModificar();
    }//GEN-LAST:event_jRadioModificarActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        iniciarComponentes();
        limpiarCampos();
        habilitarBotones();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public void retornarDatosSedes() {
        String[] datos = ControladorSede.extraerSede(identificacion);
        jTextFieldIdentificacion.setText(datos[0]);
        jTextFieldIdEmpleado.setText(datos[1]);
        jTextFieldNombre.setText(datos[2]);
        jTextFieldDireccion.setText(datos[3]);
        jTextFieldTelefono.setText(datos[4]);
        jTextFieldFechaCreacion.setText(datos[5]);
    }

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        identificacion = jTextFieldIdentificacion.getText();
        if (ControladorSede.consultarSede(identificacion) && jRadioModificar.isSelected()) {
            retornarDatosSedes();
            eventosBuscar();
        } else if (ControladorSede.consultarSede(identificacion) == false) {
            JOptionPane.showMessageDialog(null, "No existe");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarSedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioModificar;
    private javax.swing.JRadioButton jRadioRegistrar;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldFechaCreacion;
    private javax.swing.JTextField jTextFieldIdEmpleado;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
