/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JDateChooser;
import controladores.ControladorEvento;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class RegistrarEventos extends JFrame {

    private String identificacion;
    private String id_empleado;
    private String nombre;
    private String descripcion;
    private String fecha_inicio;
    private String fecha_creacion;
    private String fecha_fin;
    private String horario;
    private String horas;
    private String valor;
    private String lugar;
    private String cupos;
    private String estado;
    ControladorEvento ControladorEvento = new ControladorEvento();

    @Override
    public void setDefaultCloseOperation(int i) {
        super.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form RegistrarSedes
     */
    public RegistrarEventos() {
        initComponents();
        setResizable(false);
        iniciarComponentes();
        limpiarCampos();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldIdEmpleado = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jTextFieldFechaCreacion = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jRadioRegistrar = new javax.swing.JRadioButton();
        jRadioModificar = new javax.swing.JRadioButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldFechaFin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldHorario = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldCupos = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Eventos");

        jLabel2.setText("Identificacion");

        jLabel3.setText("Id empleado");

        jLabel4.setText("Nombre");

        jLabel5.setText("Descripcion");

        jLabel6.setText("Fecha Creacion");

        jLabel7.setText("Fecha Inicio");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jRadioRegistrar.setText("Registrar");
        jRadioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioRegistrarActionPerformed(evt);
            }
        });

        jRadioModificar.setText("Modificar");
        jRadioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioModificarActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha Fin");

        jLabel9.setText("Horario");

        jLabel10.setText("Horas");

        jTextFieldHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor");

        jLabel12.setText("Lugar");

        jLabel13.setText("Cupos");

        jLabel14.setText("Estado");

        jTextFieldLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLugarActionPerformed(evt);
            }
        });

        jTextFieldCupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCuposActionPerformed(evt);
            }
        });

        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(36, 36, 36))))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldIdEmpleado)
                            .addComponent(jTextFieldIdentificacion)
                            .addComponent(jTextFieldDescripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOk)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBuscar))
                            .addComponent(jTextFieldFechaInicio)
                            .addComponent(jTextFieldFechaCreacion)
                            .addComponent(jTextFieldFechaFin)
                            .addComponent(jTextFieldHorario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldValor)
                            .addComponent(jTextFieldLugar)
                            .addComponent(jTextFieldCupos)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldEstado)
                                .addGap(81, 81, 81))
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioRegistrar)
                    .addComponent(jRadioModificar))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jRadioRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonBuscar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void iniciarComponentes() {
        identificacion = "";
        id_empleado = "";
        nombre = "";
        descripcion = "";
        fecha_inicio = "";
        fecha_creacion = "";
        fecha_fin = "";
        horario = "";
        horas = "";
        valor = "";
        lugar = "";
        cupos = "";
        estado = "";
        jButtonBuscar.setEnabled(false);
    }

    public final void limpiarCampos() {
        jTextFieldIdentificacion.setText("");
        jTextFieldIdEmpleado.setText("");
        jTextFieldNombre.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldFechaInicio.setText("");
        jTextFieldFechaCreacion.setText("");
        jTextFieldFechaFin.setText("");
        jTextFieldHorario.setText("");
        jTextFieldHoras.setText("");
        jTextFieldValor.setText("");
        jTextFieldLugar.setText("");
        jTextFieldCupos.setText("");
        jTextFieldEstado.setText("");
    }

    public void tomarCampos() {
        identificacion = jTextFieldIdentificacion.getText();
        id_empleado = jTextFieldIdEmpleado.getText();
        nombre = jTextFieldNombre.getText();
        descripcion = jTextFieldDescripcion.getText();
        fecha_inicio = jTextFieldFechaInicio.getText();
        fecha_fin = jTextFieldFechaFin.getText();
        fecha_creacion = jTextFieldFechaCreacion.getText();
        horario = jTextFieldHorario.getText();
        horas = jTextFieldHoras.getText();
        valor = jTextFieldValor.getText();
        lugar = jTextFieldLugar.getText();
        cupos = jTextFieldCupos.getText();
        estado = jTextFieldEstado.getText();
    }

    public int validarCampos() {
        identificacion = jTextFieldIdentificacion.getText();
        id_empleado = jTextFieldIdEmpleado.getText();
        nombre = jTextFieldNombre.getText();
        descripcion = jTextFieldDescripcion.getText();
        fecha_inicio = jTextFieldFechaInicio.getText();
        fecha_creacion = jTextFieldFechaCreacion.getText();
        fecha_fin = jTextFieldFechaFin.getText();
        horario = jTextFieldHorario.getText();
        horas = jTextFieldHoras.getText();
        valor = jTextFieldValor.getText();
        lugar = jTextFieldLugar.getText();
        cupos = jTextFieldCupos.getText();
        estado = jTextFieldEstado.getText();
        if (identificacion.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", identificacion)) {
            return 1;
        } else if (id_empleado.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", id_empleado)) {
            return 2;
        } else if (nombre.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[a-zA-Z ]+", nombre)) {
            return 3;
        } else if (descripcion.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[a-zA-Z ]+", descripcion)) {
            return 4;
        } else if (fecha_creacion.isEmpty()) {
            return 7;
        } else if (!fecha_creacion.contains("-") || !fecha_creacion.contains(":")) {
            return 5;
        } else if (fecha_inicio.isEmpty()) {
            return 7;
        } else if (!fecha_inicio.contains("-") || !fecha_inicio.contains(":")) {
            return 6;
        } else if (fecha_fin.isEmpty()) {
            return 7;
        } else if (!fecha_fin.contains("-") || !fecha_fin.contains(":")) {
            return 8;
        } else if (horario.isEmpty()) {
            return 7;
        } else if (!horario.contains("-") || !horario.contains(":")) {
            return 9;
        } else if (horas.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", horas)) {
            return 10;
        } else if (valor.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", valor)) {
            return 11;
        } else if (lugar.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[a-zA-Z0-9 ]+", lugar)){
            return 12;
        } else if (cupos.isEmpty()) {
            return 7;
        } else if (!Pattern.matches("[0-9]+", cupos)) {
            return 13;
        }

        return 0;
    }

    public void habilitarBotones() {
        jRadioModificar.setEnabled(true);
        jRadioRegistrar.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonOk.setEnabled(true);
        jTextFieldDescripcion.setEditable(true);
        jTextFieldFechaCreacion.setEditable(true);
        jTextFieldIdEmpleado.setEditable(true);
        jTextFieldIdentificacion.setEditable(true);
        jTextFieldNombre.setEditable(true);
        jTextFieldFechaInicio.setEditable(true);
        jRadioModificar.setSelected(false);
        jRadioRegistrar.setSelected(false);
    }
    private void jRadioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioRegistrarActionPerformed
        // TODO add your handling code here:
        jRadioModificar.setEnabled(false);
    }//GEN-LAST:event_jRadioRegistrarActionPerformed

    private void mostrarMensajesValidaciones(int numero) {
        switch (numero) {
            case 1:
                JOptionPane.showMessageDialog(null, "El campo identifiacion sólo debe contener números");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "El campo id empleado sólo debe contener números");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "El campo nombre sólo debe contener letras");
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "La descripcion no permite numeros o caracteres especiales");
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "La fecha de creación no permite letras o caracteres especiales");
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "La fecha de inicio no permite letras o caracteres especiales");
                break;
            case 7:
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
                break;
            case 8:
                JOptionPane.showMessageDialog(null, "La fecha de fin no permite letras o caracteres especiales");
                break;
            case 9:
                JOptionPane.showMessageDialog(null, "El campo horario no permite letras o caracteres especiales");
                break;
            case 10:
                JOptionPane.showMessageDialog(null, "El campo horas sólo permite números");
                break; 
            case 11:
                JOptionPane.showMessageDialog(null, "El campo valor sólo permite números");
                break;      
            case 12:
                JOptionPane.showMessageDialog(null, "El campo lugar no permite caracteres especiales");
                break;
            case 13:
                JOptionPane.showMessageDialog(null, "El campo cupos sólo permite números");
                break;      
            case 0:
                JOptionPane.showMessageDialog(null, "Éxito");
                limpiarCampos();
                break;
            default:
                break;
        }
    }
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        if (jRadioRegistrar.isSelected()) {
            tomarCampos();
            int respuesta = validarCampos();
            mostrarMensajesValidaciones(respuesta);
            if (respuesta == 0) {
                ControladorEvento.registrarEvento(id_empleado, identificacion, nombre, descripcion, fecha_creacion, fecha_inicio, fecha_fin, horario, horas, valor, lugar, cupos, estado);
                limpiarCampos();
                habilitarBotones();
            }
        }
        if (jRadioModificar.isSelected()) {
            tomarCampos();
            int respuesta = validarCampos();
            mostrarMensajesValidaciones(respuesta);
            if (respuesta == 0) {
                ControladorEvento.editarEvento(id_empleado, identificacion, nombre, descripcion, fecha_creacion, fecha_inicio, fecha_fin, horario, horas, valor, lugar, cupos, estado);
                limpiarCampos();
                habilitarBotones();
            }
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    /*private void validarBeta()
    {
        ControladorEvento controlador = new ControladorEvento() ;
        controlador.validarDatosModif(identificacion, id_empleado, nombre, descripcion, fecha_inicio, fecha_creacion);
    }*/
    private void eventosModificar() {
        jRadioRegistrar.setEnabled(false);
        jRadioRegistrar.setSelected(false);
        jButtonOk.setEnabled(false);
        jButtonCancel.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        jTextFieldIdEmpleado.setEditable(false);
        jTextFieldNombre.setEditable(false);
        jTextFieldDescripcion.setEditable(false);
        jTextFieldFechaInicio.setEditable(false);
        jTextFieldFechaCreacion.setEditable(false);
    }

    private void eventosBuscar() {
        jTextFieldIdentificacion.setEditable(false);
        jTextFieldIdEmpleado.setEditable(true);
        jTextFieldNombre.setEditable(true);
        jTextFieldDescripcion.setEditable(true);
        jTextFieldFechaInicio.setEditable(true);
        jTextFieldFechaCreacion.setEditable(true);
        jButtonBuscar.setEnabled(false);
        jButtonOk.setEnabled(true);
    }

    private void jRadioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioModificarActionPerformed
        // TODO add your handling code here:
        eventosModificar();
    }//GEN-LAST:event_jRadioModificarActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        iniciarComponentes();
        limpiarCampos();
        habilitarBotones();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public void retornarDatosEventos() {
        String[] datos = ControladorEvento.extraerEvento(identificacion);
        jTextFieldIdentificacion.setText(datos[0]);
        jTextFieldIdEmpleado.setText(datos[1]);
        jTextFieldNombre.setText(datos[2]);
        jTextFieldDescripcion.setText(datos[3]);
        jTextFieldFechaCreacion.setText(datos[4]);
        jTextFieldFechaInicio.setText(datos[5]);
        jTextFieldFechaFin.setText(datos[6]);
        jTextFieldHorario.setText(datos[7]);
        jTextFieldHoras.setText(datos[8]);
        jTextFieldValor.setText(datos[9]);
        jTextFieldLugar.setText(datos[10]);
        jTextFieldCupos.setText(datos[11]);
        jTextFieldEstado.setText(datos[12]);
    }

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        identificacion = jTextFieldIdentificacion.getText();
        if (ControladorEvento.consultarEvento(identificacion)) {
            retornarDatosEventos();
            eventosBuscar();

        } else {
            JOptionPane.showMessageDialog(null, "No existe");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorasActionPerformed

    private void jTextFieldLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLugarActionPerformed

    private void jTextFieldCuposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCuposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCuposActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioModificar;
    private javax.swing.JRadioButton jRadioRegistrar;
    private javax.swing.JTextField jTextFieldCupos;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldFechaCreacion;
    private javax.swing.JTextField jTextFieldFechaFin;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldIdEmpleado;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
