/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import controladores.ControladorSede;
import javax.swing.JOptionPane;
/**
 *
 * @author daniel
 */
public class VentanaModificarSede extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificarSede
     */
    public VentanaModificarSede() {
        initComponents();
        jOptionPaneError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificar = new javax.swing.JButton();
        jLabelIdentificacion = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelNota1 = new javax.swing.JLabel();
        jLabelNota2 = new javax.swing.JLabel();
        jOptionPaneError = new javax.swing.JOptionPane();
        jTextFieldDirector = new javax.swing.JTextField();
        jLabelDirector = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabelIdentificacion.setText("Identificación de la Sede :");
        getContentPane().add(jLabelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabelNombre.setText("Nombre de la Sede:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabelDireccion.setText("Dirección de la Sede: ");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabelTelefono.setText("Teléfono de la Sede: ");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 240, 30));

        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 240, 30));

        jTextFieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 30));

        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 240, 30));

        jLabelNota1.setFont(new java.awt.Font("Ubuntu", 1, 8)); // NOI18N
        jLabelNota1.setText("* Todos los campos son obligatorios.");
        getContentPane().add(jLabelNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabelNota2.setFont(new java.awt.Font("Ubuntu", 1, 8)); // NOI18N
        jLabelNota2.setText("Al finalizar se modificar solo la sede con el identificador indicado.");
        getContentPane().add(jLabelNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(jOptionPaneError, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 450, 20, 10));

        jTextFieldDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirectorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 240, 30));

        jLabelDirector.setText("Director de la Sede: ");
        getContentPane().add(jLabelDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(10, 56, 86));
        jLabelFondo.setForeground(new java.awt.Color(20, 35, 118));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
       // System.out.println("Click!");
        String id = jTextFieldIdentificacion.getText();
        String nombre = jTextFieldNombre.getText();
        String dir = jTextFieldDireccion.getText(); 
        String tel = jTextFieldTelefono.getText(); 
        String direc = jTextFieldDirector.getText(); 
                                   
        ControladorSede controlador = new ControladorSede() ;
        if( controlador.validarDatosModif(direc, direc, nombre, direc, tel, direc))
          {  
            System.out.println("datosValidos");
            //controlador.modificarSedesid, nombre, dir,tel, direc );
        }
        
        
       else if(controlador.datosVacios(direc, direc, nombre, direc, tel, direc).equals("Todos los campos son obligatorios."))
       {
          
           jOptionPaneError.showMessageDialog(null,"Todos los campos son obligatorios.","##ERROR##", JOptionPane.INFORMATION_MESSAGE);
          
       }
       else if (controlador.datosIdentificacion(direc, direc, nombre, direc, tel, direc).equals("Identificación con uno o varios caracteres inválidos."))
           jOptionPaneError.showMessageDialog(null,"Identificación con uno o varios caracteres inválidos.","##ERROR##", JOptionPane.INFORMATION_MESSAGE);
           
       else if (controlador.datosNombre(direc, direc, nombre, direc, tel, direc).equals("Nombre con uno o varios caracteres inválidos."))
           jOptionPaneError.showMessageDialog(null,"Nombre con uno o varios caracteres inválidos.", "##ERROR##", JOptionPane.INFORMATION_MESSAGE);
       else if (controlador.datosTelefono(direc, direc, nombre, direc, tel, direc).equals("Teléfono con uno o varios caracteres inválidos."))
           jOptionPaneError.showMessageDialog(null,"Teléfono con uno o varios caracteres inválidos.", "##ERROR##", JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionActionPerformed
        // TODO add  your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacionActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirectorActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificarSede().setVisible(true);
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIdentificacion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNota1;
    private javax.swing.JLabel jLabelNota2;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JOptionPane jOptionPaneError;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
